# Read build script documentation https://docs.armbian.com/Developer-Guide_Build-Options/
# for detailed explanation of these options and for additional options not listed here

KERNEL_CONFIGURE="no" # leave empty to select each time, set to "yes" or "no" to skip dialog prompt
CLEAN_LEVEL=""      # comma-separated list of clean targets:
:                   # --> "make-atf" = make clean for ATF, if it is built.
:                   # --> "make-uboot" = make clean for uboot, if it is built.
:                   # --> "make-kernel" = make clean for kernel, if it is built. very slow.
:                   # --> "debs" = delete packages in "./output/debs"; debs are re-downloaded (if available) or re-built.
:                   # --> "alldebs" = delete all packages in "./output/debs",
:                   # --> "images" = delete "./output/images",
:                   # --> "cache" = delete "./output/cache",
:                   # --> "sources" = delete "./sources"
:                   # --> "oldcache" = remove old cached rootfs except for the newest 8 files
:                   # --> *important*: "make" by itself has disabled, since Armbian knows how to handle Make timestamping now.

# DEST_LANG="en_US.UTF-8" # Example: "sl_SI.UTF-8" Default: "en_US.UTF-8"
BOARD=rock-5a
BRANCH=edge
BUILD_DESKTOP=yes
BUILD_MINIMAL=no
DESKTOP_APPGROUPS_SELECTED="3dsupport browsers desktop_tools editors internet internet-tools languages programming remote_desktop"
DESKTOP_ENVIRONMENT=xfce
DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base
KERNEL_CONFIGURE=no
RELEASE=jammy
NETWORKING_STACK=network-manager
ENABLE_EXTENSIONS=mesa-vpu,preset-firstrun
EXTRAWIFI=yes
DISABLE_IPV6=false
PACKAGE_LIST_ADDITIONAL="vim netfilter-persistent iw build-essential libssl-dev libnl-3-dev libnl-genl-3-dev pkg-config libdbus-1-dev libreadline-dev"
KERNEL_GIT=shallow
ARMBIAN_CLI_RELAUNCH_ENVS=([HTTP_PROXY]=http://172.28.128.1:2334 [HTTPS_PROXY]=http://172.28.128.1:2334)
SHARE_LOG=no

# advanced
INSTALL_HEADERS="" # install kernel headers package
DOWNLOAD_MIRROR="" # set to "china" to use chinese mirrors # @TODO: this needs review and test while running in mainland china
CARD_DEVICE=""     # device name /dev/sdx of your SD card to burn directly to the card when done
